### ISSUE TITLE
更新立委名單

### ISSUE THREAD

**Issue by Yukaii** [Disfactory/findTaiwanLegislator#3]
- 新國會 2024/2/1 上任

**Comment by yoyo930021** [comment]
選舉區資料 502，先暫時拿 109 年的選舉區代替，應該沒有變吧 ?
https://data.gov.tw/dataset/13119

**Comment by yoyo930021** [comment]
測試資料裡的六個立委，只有一個有換人 O.O

**Comment by yoyo930021** [comment]
已更新 2024
